/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssumptionsRouteImport } from './routes/assumptions'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ImportRouteImport } from './routes/import'
import { Route as InputsRouteImport } from './routes/inputs'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as MarketTaxRouteImport } from './routes/market-tax'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProjectionsRouteImport } from './routes/projections'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RetirementRouteImport } from './routes/retirement'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StressRouteImport } from './routes/stress'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ApiPublicCronSnapshotRouteImport } from './routes/api/public/cron/snapshot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssumptionsRoute = AssumptionsRouteImport.update({
  id: '/assumptions',
  path: '/assumptions',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const InputsRoute = InputsRouteImport.update({
  id: '/inputs',
  path: '/inputs',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketTaxRoute = MarketTaxRouteImport.update({
  id: '/market-tax',
  path: '/market-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectionsRoute = ProjectionsRouteImport.update({
  id: '/projections',
  path: '/projections',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RetirementRoute = RetirementRouteImport.update({
  id: '/retirement',
  path: '/retirement',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StressRoute = StressRouteImport.update({
  id: '/stress',
  path: '/stress',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronSnapshotRoute = ApiPublicCronSnapshotRouteImport.update({
  id: '/api/public/cron/snapshot',
  path: '/api/public/cron/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assumptions': typeof AssumptionsRoute
  '/calendar': typeof CalendarRoute
  '/disclaimer': typeof DisclaimerRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/inputs': typeof InputsRoute
  '/insights': typeof InsightsRoute
  '/integrations': typeof IntegrationsRoute
  '/ledger': typeof LedgerRoute
  '/market-tax': typeof MarketTaxRoute
  '/methodology': typeof MethodologyRoute
  '/plan': typeof PlanRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/projections': typeof ProjectionsRoute
  '/research': typeof ResearchRoute
  '/retirement': typeof RetirementRoute
  '/review': typeof ReviewRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/stress': typeof StressRoute
  '/unlock': typeof UnlockRoute
  '/watchlist': typeof WatchlistRoute
  '/api/public/cron/snapshot': typeof ApiPublicCronSnapshotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assumptions': typeof AssumptionsRoute
  '/calendar': typeof CalendarRoute
  '/disclaimer': typeof DisclaimerRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/inputs': typeof InputsRoute
  '/insights': typeof InsightsRoute
  '/integrations': typeof IntegrationsRoute
  '/ledger': typeof LedgerRoute
  '/market-tax': typeof MarketTaxRoute
  '/methodology': typeof MethodologyRoute
  '/plan': typeof PlanRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/projections': typeof ProjectionsRoute
  '/research': typeof ResearchRoute
  '/retirement': typeof RetirementRoute
  '/review': typeof ReviewRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/stress': typeof StressRoute
  '/unlock': typeof UnlockRoute
  '/watchlist': typeof WatchlistRoute
  '/api/public/cron/snapshot': typeof ApiPublicCronSnapshotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assumptions': typeof AssumptionsRoute
  '/calendar': typeof CalendarRoute
  '/disclaimer': typeof DisclaimerRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/inputs': typeof InputsRoute
  '/insights': typeof InsightsRoute
  '/integrations': typeof IntegrationsRoute
  '/ledger': typeof LedgerRoute
  '/market-tax': typeof MarketTaxRoute
  '/methodology': typeof MethodologyRoute
  '/plan': typeof PlanRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/projections': typeof ProjectionsRoute
  '/research': typeof ResearchRoute
  '/retirement': typeof RetirementRoute
  '/review': typeof ReviewRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/stress': typeof StressRoute
  '/unlock': typeof UnlockRoute
  '/watchlist': typeof WatchlistRoute
  '/api/public/cron/snapshot': typeof ApiPublicCronSnapshotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assumptions'
    | '/calendar'
    | '/disclaimer'
    | '/goals'
    | '/import'
    | '/inputs'
    | '/insights'
    | '/integrations'
    | '/ledger'
    | '/market-tax'
    | '/methodology'
    | '/plan'
    | '/portfolio'
    | '/privacy'
    | '/projections'
    | '/research'
    | '/retirement'
    | '/review'
    | '/scenarios'
    | '/settings'
    | '/stress'
    | '/unlock'
    | '/watchlist'
    | '/api/public/cron/snapshot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assumptions'
    | '/calendar'
    | '/disclaimer'
    | '/goals'
    | '/import'
    | '/inputs'
    | '/insights'
    | '/integrations'
    | '/ledger'
    | '/market-tax'
    | '/methodology'
    | '/plan'
    | '/portfolio'
    | '/privacy'
    | '/projections'
    | '/research'
    | '/retirement'
    | '/review'
    | '/scenarios'
    | '/settings'
    | '/stress'
    | '/unlock'
    | '/watchlist'
    | '/api/public/cron/snapshot'
  id:
    | '__root__'
    | '/'
    | '/assumptions'
    | '/calendar'
    | '/disclaimer'
    | '/goals'
    | '/import'
    | '/inputs'
    | '/insights'
    | '/integrations'
    | '/ledger'
    | '/market-tax'
    | '/methodology'
    | '/plan'
    | '/portfolio'
    | '/privacy'
    | '/projections'
    | '/research'
    | '/retirement'
    | '/review'
    | '/scenarios'
    | '/settings'
    | '/stress'
    | '/unlock'
    | '/watchlist'
    | '/api/public/cron/snapshot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssumptionsRoute: typeof AssumptionsRoute
  CalendarRoute: typeof CalendarRoute
  DisclaimerRoute: typeof DisclaimerRoute
  GoalsRoute: typeof GoalsRoute
  ImportRoute: typeof ImportRoute
  InputsRoute: typeof InputsRoute
  InsightsRoute: typeof InsightsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LedgerRoute: typeof LedgerRoute
  MarketTaxRoute: typeof MarketTaxRoute
  MethodologyRoute: typeof MethodologyRoute
  PlanRoute: typeof PlanRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectionsRoute: typeof ProjectionsRoute
  ResearchRoute: typeof ResearchRoute
  RetirementRoute: typeof RetirementRoute
  ReviewRoute: typeof ReviewRoute
  ScenariosRoute: typeof ScenariosRoute
  SettingsRoute: typeof SettingsRoute
  StressRoute: typeof StressRoute
  UnlockRoute: typeof UnlockRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiPublicCronSnapshotRoute: typeof ApiPublicCronSnapshotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assumptions': {
      id: '/assumptions'
      path: '/assumptions'
      fullPath: '/assumptions'
      preLoaderRoute: typeof AssumptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inputs': {
      id: '/inputs'
      path: '/inputs'
      fullPath: '/inputs'
      preLoaderRoute: typeof InputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-tax': {
      id: '/market-tax'
      path: '/market-tax'
      fullPath: '/market-tax'
      preLoaderRoute: typeof MarketTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projections': {
      id: '/projections'
      path: '/projections'
      fullPath: '/projections'
      preLoaderRoute: typeof ProjectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retirement': {
      id: '/retirement'
      path: '/retirement'
      fullPath: '/retirement'
      preLoaderRoute: typeof RetirementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stress': {
      id: '/stress'
      path: '/stress'
      fullPath: '/stress'
      preLoaderRoute: typeof StressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/snapshot': {
      id: '/api/public/cron/snapshot'
      path: '/api/public/cron/snapshot'
      fullPath: '/api/public/cron/snapshot'
      preLoaderRoute: typeof ApiPublicCronSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssumptionsRoute: AssumptionsRoute,
  CalendarRoute: CalendarRoute,
  DisclaimerRoute: DisclaimerRoute,
  GoalsRoute: GoalsRoute,
  ImportRoute: ImportRoute,
  InputsRoute: InputsRoute,
  InsightsRoute: InsightsRoute,
  IntegrationsRoute: IntegrationsRoute,
  LedgerRoute: LedgerRoute,
  MarketTaxRoute: MarketTaxRoute,
  MethodologyRoute: MethodologyRoute,
  PlanRoute: PlanRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectionsRoute: ProjectionsRoute,
  ResearchRoute: ResearchRoute,
  RetirementRoute: RetirementRoute,
  ReviewRoute: ReviewRoute,
  ScenariosRoute: ScenariosRoute,
  SettingsRoute: SettingsRoute,
  StressRoute: StressRoute,
  UnlockRoute: UnlockRoute,
  WatchlistRoute: WatchlistRoute,
  ApiPublicCronSnapshotRoute: ApiPublicCronSnapshotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
